### ISSUE TITLE
Ideas for removing the last `unsafe`

### ISSUE THREAD

**Issue by briansmith** [alicemaz/rust-base64#34]
The work to remove the other uses of `unsafe` was awesome. However, I do think it is worthwhile to try to remove all of the uses of `unsafe`, of which there is currently only one. I think a lot of people are like me and think that `unsafe` should only be used as a last resort. I think there are alternatives that are workable and even better in terms of usability for certain circumstances than what we have now.

/cc @marshallpierce @alicemaz

Here are three ideas for removing the last use of `unsafe`:

1. Just do it, on the assumption the difference in `encode_config_buf()` performance isn't that critical, because very few applications need high-performance base64 *encoding* of large data.

2. Change the signature to use move semantics:

Old:
```rust
pub fn encode_config_buf<T: ?Sized + AsRef<[u8]>>(input: &T, config: Config, buf: &mut String) {
}
```
New:
```
pub fn encode_config_buf<T: ?Sized + AsRef<[u8]>>(input: &T, config: Config, buf: String) -> String {
    let buf_bytes = buf.into_bytes();
    ....
    String::from_utf8(buf_bytes)
}
```

3. Change the signature to use `&mut Vec` instead of `&mut String`. A caller that has a `String` would then be able to decide whether they want to use `as_mut_vec()` for performance reasons, or whether they want to use move semantics (like suggestion 2 above), or whether they want to start with a `Vec`. This also has the advantage that if you have a `Vec<u8>` already, e.g. because you're writing base64 data into some kind of binary or otherwise non-UTF-8 array, you don't require any extra allocations.

**Comment by marshallpierce** [comment]
I like the third approach -- I'd already been mulling the merits of allowing users to provide a `Vec<u8>` for convenience reasons, and the lack of unsafe in that code path would be a nice benefit. I wonder if maybe we should even expose the ability to write to a slice?

Also note that #33 involves one other unsafe (doing the same sort of thing as the existing one).

**Comment by marshallpierce** [comment]
#33 no longer uses unsafe (but users have the option to reimplement a bit of it if they need the performance). 

Creating a variant that encodes into a `Vec<u8>` is easy enough. Supporting the existing `encode_config_buf<T: ?Sized + AsRef<[u8]>>(input: &T, config: Config, buf: &mut String)` is pretty tricky without unsafe, though. 

- We could allocate an extra `Vec<u8>`, encode into that, then append it to the string. This is easy, but incurs allocation overhead and of course a memory copy.
- We could do it with a fixed stack resident buffer if #33 was extended to allow more line wrap configurations, which would mean no extra heap allocation at the price of implementation complexity. It _might_ be faster than the other alternative since it may have better memory locality, but hard to say how different memory prefetchers might behave.

**Comment by marshallpierce** [comment]
The latter of the above points lends weight to #60 -- if we didn't have line wraps, we could `push_str` (with utf8 checking overhead) via `ChunkedEncoder`.

**Comment by marshallpierce** [comment]
No more unsafe.
