### ISSUE TITLE
Big performance regression between 0.5.2 and 0.6.0

### ISSUE THREAD

**Issue by JordiPolo** [alicemaz/rust-base64#51]
I was playing with https://github.com/kostya/benchmarks and upgraded the version of base64 for rust to 0.7.0 and got a big performance regression.
Experimenting further the problem happened between 0.5.2 and 0.6.0
[This commit](https://github.com/alicemaz/rust-base64/commit/cefe67e0a0536dfebcdd49a763c8ff5e0f663834#diff-25d902c24283ab8cfbac54dfa101ad31) hints at a performance loss and how to fix it but it talks about 15% performance loss while the above benchmark for encoding went in my machine from 20 seconds to 120 seconds. 
Maybe something else is going on?

**Comment by JordiPolo** [comment]
Ok, nevermind. I was running develpment builds, release builds have roughly the same performance in both versions.
I will not close the issue but maybe development builds being slower is known already

**Comment by marshallpierce** [comment]
Whew! Had me worried for a second there, and I went and re-ran old and new benchmarks to confirm no regression. :)

That's a known issue (with basically all rust code): development builds will be much much slower because the compiler doesn't spend nearly as much time trying to generate fast code. In particular, inlining is crucial here.
